name: Build Project - macOS

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/**'
      - 'CMakeLists.txt'
      - '.github/workflows/build_macos.yml'
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write       # Required for actions/upload-release-asset to upload release asset
    runs-on: macos-latest

    env:
      PROJECT_NAME: ${{ github.event.repository.name }}
      PROJECT_RELEASE_PATH: ${{ github.event.repository.name }}_dev_macos
      # CMake project/target name, fixed in CMakeLists.txt
      CMAKE_TARGET_NAME: raylib-game-template

    steps:
    - name: Checkout this repo
      uses: actions/checkout@master

    - name: Setup Release Paths
      run: |
        echo "PROJECT_RELEASE_PATH=${{ env.PROJECT_NAME }}_v${{ github.event.release.tag_name }}_macos" >> $GITHUB_ENV
      shell: bash
      if: github.event_name == 'release' && github.event.action == 'published'

    - name: Build Product
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build

    - name: Generate Artifacts
      run: |
        mkdir -p ${{ env.PROJECT_RELEASE_PATH }}
        cp -r build/${{ env.CMAKE_TARGET_NAME }}/. ${{ env.PROJECT_RELEASE_PATH }}/
        cp README.md LICENSE ${{ env.PROJECT_RELEASE_PATH }}/
        ls ${{ env.PROJECT_RELEASE_PATH }}
        7z a ./${{ env.PROJECT_RELEASE_PATH }}.zip ./${{ env.PROJECT_RELEASE_PATH }}
      shell: bash

    - name: Upload Artifacts
      uses: actions/upload-artifact@v7
      with:
        name: ${{ env.PROJECT_RELEASE_PATH }}.zip
        path: |
            ./${{ env.PROJECT_RELEASE_PATH }}
            !./${{ env.PROJECT_RELEASE_PATH }}.zip

    - name: Upload Artifact to Release
      uses: softprops/action-gh-release@v3
      with:
        files: ${{ env.PROJECT_RELEASE_PATH }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: github.event_name == 'release' && github.event.action == 'published'
